# Generated by Django 2.2 on 2019-05-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('form_code', models.SlugField(verbose_name='Code')),
                ('form_title', models.CharField(max_length=255, verbose_name='Title')),
                ('form_set', models.TextField(verbose_name='Formset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('form_code', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='FormObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('custom_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_extra_fields.Form')),
            ],
            options={
                'unique_together': {('object_id', 'custom_form'), ('object_id', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.SlugField(max_length=255, verbose_name='Field name')),
                ('field_type', models.CharField(choices=[('ControlText', 'Short text'), ('ControlCheckBox', 'Check box'), ('ControlDate', 'Date')], max_length=50, verbose_name='Field type')),
                ('field_parms', models.TextField(verbose_name='Parameters')),
                ('mandatory', models.BooleanField(verbose_name='It is mandatory')),
                ('custom_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='model_extra_fields.Form')),
            ],
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Value')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_extra_fields.ExtraField')),
                ('form_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_extra_fields.FormObject')),
            ],
            options={
                'unique_together': {('field', 'form_object')},
            },
        ),
    ]
