# Generated by Django 2.2 on 2019-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_extra_fields', '0002_auto_20190523_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtypefields',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='formtypefields',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
