# Generated by Django 2.2 on 2019-05-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_extra_fields', '0005_auto_20190523_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtypefields',
            name='form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='model_extra_fields.FormType'),
        ),
    ]
