# Generated by Django 2.2 on 2019-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_extra_fields', '0007_auto_20190523_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtypefields',
            name='field_label',
        ),
        migrations.AddField(
            model_name='formtypefields',
            name='field_name',
            field=models.SlugField(default=None, max_length=255, verbose_name='Field name'),
            preserve_default=False,
        ),
    ]
