# Generated by Django 2.2 on 2019-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('model_extra_fields', '0012_auto_20190523_1836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formtypeobject',
            unique_together={('object_id', 'content_type'), ('object_id', 'form_type')},
        ),
    ]
