# Generated by Django 2.2 on 2019-05-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0003_auto_20190523_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formtypefields',
            options={},
        ),
        migrations.RemoveField(
            model_name='formtypefields',
            name='order',
        ),
    ]
