# Generated by Django 2.2 on 2019-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0004_auto_20190523_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='form_code',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formtype',
            name='form_name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
