# Generated by Django 2.2 on 2019-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0006_auto_20190523_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtype',
            name='form_code',
            field=models.SlugField(unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='formtypefields',
            name='field_label',
            field=models.SlugField(max_length=255, verbose_name='Field label'),
        ),
    ]
