# Generated by Django 2.2 on 2019-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0008_auto_20190523_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='form_set',
            field=models.TextField(default=None, verbose_name='Formset'),
            preserve_default=False,
        ),
    ]
