# Generated by Django 2.2 on 2019-05-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_forms', '0009_formtype_form_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormTypeFields',
            new_name='FormTypeField',
        ),
    ]
